/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paqueteria;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author willians
 */
public class ControlAdmin extends javax.swing.JInternalFrame {
    Controlador cn1;
    int opcion = 0;
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form ControlAdmin
     */
    public ControlAdmin(Controlador cn1, int opcion) {
        initComponents();
        this.cn1 = cn1;
        this.opcion = opcion;
        if (opcion==1){
            panelUsuarios.setVisible(false);
            panelPuntos.setVisible(true);
            
            modelo.addColumn("RUTA");
            modelo.addColumn("#PUNTO");
            modelo.addColumn("NOMBRE");
            modelo.addColumn("COBRO");
            modelo.addColumn("ENCARGADO");
            tablaPuntos.setModel(modelo);
        } else if (opcion==0) {
            panelUsuarios.setVisible(true);
            panelPuntos.setVisible(false);
        } else {
            System.out.print("vamos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelUsuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelPuntos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPuntos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_BuscarPunto = new javax.swing.JTextField();
        visualizarPuntos = new javax.swing.JComboBox<>();
        btn_BuscarPuntos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panelRutas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("USUARIOS");

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        jButton1.setText("SELECCIONAR");

        jButton2.setText("ELIMINAR");

        jButton3.setText("CREAR NUEVO");

        jButton4.setText("MODIFICAR");

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                    .addGroup(panelUsuariosLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(105, 105, 105)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        tablaPuntos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaPuntos);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PUNTOS DE CONTROL");

        visualizarPuntos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "#Ruta", "Encargado", "NombrePunto", "NombreRuta" }));
        visualizarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarPuntosActionPerformed(evt);
            }
        });

        btn_BuscarPuntos.setText("BUSCAR");
        btn_BuscarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarPuntosActionPerformed(evt);
            }
        });

        jLabel3.setText("BUSQUEDA POR:");

        javax.swing.GroupLayout panelPuntosLayout = new javax.swing.GroupLayout(panelPuntos);
        panelPuntos.setLayout(panelPuntosLayout);
        panelPuntosLayout.setHorizontalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPuntosLayout.createSequentialGroup()
                        .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPuntosLayout.createSequentialGroup()
                                .addComponent(txt_BuscarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(visualizarPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_BuscarPuntos)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPuntosLayout.setVerticalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_BuscarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(visualizarPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BuscarPuntos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jLabel4.setText("RUTAS");

        javax.swing.GroupLayout panelRutasLayout = new javax.swing.GroupLayout(panelRutas);
        panelRutas.setLayout(panelRutasLayout);
        panelRutasLayout.setHorizontalGroup(
            panelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutasLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel4)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        panelRutasLayout.setVerticalGroup(
            panelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(470, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(panelUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelPuntos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelRutas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRutas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRutas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visualizarPuntosActionPerformed

    private void btn_BuscarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarPuntosActionPerformed
        if (visualizarPuntos.getSelectedIndex()==0)
        {
            mostrarTablaPuntos();
        }
        String verificador = txt_BuscarPunto.getText();
        if (!txt_BuscarPunto.getText().isBlank() && visualizarPuntos.getSelectedIndex() != 0) {
            switch (visualizarPuntos.getSelectedIndex()) {
                case 1:
                    String validos = "0123456789";
                    int contando_Correctos = 0;
                    for (int i = 0; i < verificador.length(); i++) {
                        for (int u = 0; u < validos.length(); u++) {
                            if (verificador.charAt(i) == validos.charAt(u)) {
                                contando_Correctos++;
                            }
                        }
                    }   if (contando_Correctos == verificador.length()) {
                        String sql2 = "SELECT * FROM Puntos WHERE Id_Ruta = " + Integer.parseInt(verificador);
                        mostrarTablaPuntos(sql2);
                    } else {
                        JOptionPane.showMessageDialog(null, "NO ES UN NUMERO");
                    }   break;
                case 2:
                    {
                        String sql2 = "SELECT * FROM Puntos WHERE Encargado ='" + verificador+"'";
                        mostrarTablaPuntos(sql2);
                        break;
                    }
                case 3:
                    {
                        String sql2 = "SELECT * FROM Puntos WHERE Name_Punto ='" + verificador + "'";
                        mostrarTablaPuntos(sql2);
                        break;
                    }
                case 4:
                    {
                        String sql2 = "SELECT Id_Ruta FROM Ruta WHERE Destino ='" + verificador + "'";
                        Statement st;
                        int numeroRuta=0;
                        try {
                            st = cn1.cn.createStatement();
                            ResultSet rs = st.executeQuery(sql2);
                            while (rs.next()) {
                                numeroRuta = rs.getInt("Id_Ruta");
                            }
                        } catch (SQLException e) {
                            
                        }       mostrarTablaPuntos("SELECT * FROM Puntos WHERE Id_Ruta ="+numeroRuta);
                        break;
                    }
                default:
                    break;
            }
        }
        
        
    }//GEN-LAST:event_btn_BuscarPuntosActionPerformed

    public void mostrarTablaPuntos(){
        modelo = null;
        modelo = new DefaultTableModel();
        modelo.addColumn("RUTA");
        modelo.addColumn("#PUNTO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("COBRO");
        modelo.addColumn("ENCARGADO");
        tablaPuntos.setModel(modelo);
        String sql = "SELECT * FROM Puntos";
        
        String datos[] = new String[5];
        Statement st;
        try{
            st = cn1.cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                modelo.addRow(datos);
            }
            tablaPuntos.setModel(modelo);
        }
        catch(SQLException e){
        
        }
    }
    public void mostrarTablaUsuarios(){
        /**modelo = null;
        modelo = new DefaultTableModel();
        modelo.addColumn("USUARIO");
        modelo.addColumn("PUESTO");
        modelo.addColumn("PUNTO ENCARGADO");
        tablaUsuarios.setModel(modelo);
        String sql = "SELECT * FROM Puntos";
        
        String datos[] = new String[5];
        Statement st;
        try{
            st = cn1.cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                
                modelo.addRow(datos);
            }
            tablaUsuarios.setModel(modelo);
        }
        catch(SQLException e){
        
        }**/
    }
    public void mostrarTablaPuntos(String sql){
        modelo = null;
        modelo = new DefaultTableModel();
        modelo.addColumn("RUTA");
        modelo.addColumn("#PUNTO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("COBRO");
        modelo.addColumn("ENCARGADO");
        tablaPuntos.setModel(modelo);
        
        String datos[] = new String[5];
        Statement st;
        try{
            st = cn1.cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                modelo.addRow(datos);
            }
            tablaPuntos.setModel(modelo);
        }
        catch(SQLException e){
        
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarPuntos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelPuntos;
    private javax.swing.JPanel panelRutas;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JTable tablaPuntos;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txt_BuscarPunto;
    private javax.swing.JComboBox<String> visualizarPuntos;
    // End of variables declaration//GEN-END:variables
}
