/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paqueteria;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author willians
 */
public class ControlarPaquete extends javax.swing.JInternalFrame {

    /**
     * Creates new form ControlarPaquete
     */
    public ControlarPaquete() {
        initComponents();
        btnBuscarPaqueteNuevo.setVisible(false);
    }
    public void colocarRecorrido(int cuantos){
        int distancia = (460/2);
        int distancia2 = (distancia/cuantos);
        lblMapa.setVisible(false);
        for (int u = 0; u < cuantos; u++)
        {
            JButton boton = new JButton();
            boton.setBounds((distancia2/2)+(distancia2*u*2), 150, distancia2, distancia2);
            boton.setOpaque(false);
            if (u==2){
                ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/imagenes/direccion.png"));
                boton.setIcon(new javax.swing.ImageIcon(icono.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(), 0)));
            } else 
            {
                ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/imagenes/direccionNull.png"));
                boton.setIcon(new javax.swing.ImageIcon(icono.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(), 0)));
            }
            if (u != cuantos-1){
                ImageIcon icono2 = new javax.swing.ImageIcon(getClass().getResource("/imagenes/flechaPunteada.png"));
                JLabel flecha = new JLabel(new javax.swing.ImageIcon(icono2.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(), 0)));
                flecha.setBounds((distancia2 / 2) + (distancia2 * u * 2) + distancia2, 150, distancia2, distancia2);
                lblMapa.add(flecha);
            }
            
            boton.setContentAreaFilled(false);
            boton.setBorderPainted(false);
            boton.setToolTipText("MAZATENANGO");
            lblMapa.add(boton);
        }
        lblMapa.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entBusquedaPaquete = new javax.swing.JTextField();
        btnBusquedaPaquete = new javax.swing.JButton();
        mapa = new javax.swing.JLayeredPane();
        lblRecorrido = new javax.swing.JPanel();
        lblMapa = new javax.swing.JLabel();
        btnBuscarPaqueteNuevo = new javax.swing.JButton();

        setClosable(true);
        setTitle("Busqueda del paquete");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPaqueteria.png"))); // NOI18N
        setVisible(true);

        jLabel1.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rastrea tu paquete con el codigo:");

        btnBusquedaPaquete.setText("Buscar");
        btnBusquedaPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaPaqueteActionPerformed(evt);
            }
        });

        lblRecorrido.setOpaque(false);
        lblRecorrido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MapaGondorOeste1.jpg"))); // NOI18N
        lblRecorrido.add(lblMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        mapa.setLayer(lblRecorrido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mapaLayout = new javax.swing.GroupLayout(mapa);
        mapa.setLayout(mapaLayout);
        mapaLayout.setHorizontalGroup(
            mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRecorrido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mapaLayout.setVerticalGroup(
            mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRecorrido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBuscarPaqueteNuevo.setText("Busqueda Nueva");
        btnBuscarPaqueteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPaqueteNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 482, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscarPaqueteNuevo)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entBusquedaPaquete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBusquedaPaquete)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBusquedaPaquete)
                    .addComponent(entBusquedaPaquete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarPaqueteNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaPaqueteActionPerformed
        if (!entBusquedaPaquete.getText().isBlank()){
            entBusquedaPaquete.setEditable(false);
            lblMapa.setVisible(false);
            int numero = Integer.parseInt(entBusquedaPaquete.getText());
            colocarRecorrido(numero);
            btnBuscarPaqueteNuevo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No has puesto el codigo");
        }
    }//GEN-LAST:event_btnBusquedaPaqueteActionPerformed

    private void btnBuscarPaqueteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPaqueteNuevoActionPerformed
        lblMapa.setVisible(false);
        lblMapa = null;
        lblMapa = new javax.swing.JLabel();
        lblMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MapaGondorOeste1.jpg")));
        lblMapa.setVisible(true);
        lblRecorrido.add(lblMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 370));
        btnBuscarPaqueteNuevo.setVisible(false);
        entBusquedaPaquete.setEditable(true);
    }//GEN-LAST:event_btnBuscarPaqueteNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPaqueteNuevo;
    private javax.swing.JButton btnBusquedaPaquete;
    private javax.swing.JTextField entBusquedaPaquete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMapa;
    private javax.swing.JPanel lblRecorrido;
    private javax.swing.JLayeredPane mapa;
    // End of variables declaration//GEN-END:variables
}
