/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paqueteria;

import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willians
 */
public class FrameVario extends javax.swing.JFrame {
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    NuevoPaquete nuevoPa;
    String[] clientes;
    /**
     * Creates new form FrameVario
     */
    public FrameVario(NuevoPaquete nuevo) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        nuevoPa = nuevo;
        modelo = nuevo.getModelo();
        mostrarTabla();
        btn_GenerarFactura.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        entNit = new javax.swing.JTextField();
        btn_BuscarNit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        entNombreCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFactura = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        entCiudadCliente = new javax.swing.JTextField();
        btn_GenerarFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FLASHPOINT");

        jLabel2.setText("Quetzaltenango, Quetzaltenango");

        jLabel3.setText("Atendió: ");

        jLabel4.setText("..");

        jLabel5.setText("NIT:");

        btn_BuscarNit.setText("BUSCAR");
        btn_BuscarNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarNitActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre:");

        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaFactura);

        jLabel7.setText("Ciudad:");

        btn_GenerarFactura.setText("GENERAR");
        btn_GenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenerarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btn_GenerarFactura)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(entNit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_BuscarNit))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(entNombreCliente))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)))
                            .addGap(0, 170, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(entCiudadCliente)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(460, Short.MAX_VALUE)
                .addComponent(btn_GenerarFactura)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(entNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_BuscarNit))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(entNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(entCiudadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenerarFacturaActionPerformed
        if (!entNit.getText().isBlank()) {
            for (int i = 0; i < modelo.getRowCount(); i++) {
                String codigo = modelo.getValueAt(i, 0).toString();
                String destina = modelo.getValueAt(i, 2).toString();
                String remitente = modelo.getValueAt(i, 3).toString();
                int peso = Integer.parseInt(modelo.getValueAt(i, 4).toString());
                String costo = modelo.getValueAt(i, 5).toString();
                String priori = modelo.getValueAt(i, 6).toString();
                boolean priorizacion = false;
                if (!priori.equalsIgnoreCase("no")) {
                    priorizacion = true;
                }
                Calendar c1 = new GregorianCalendar();
                int dia = c1.get(Calendar.DATE);
                int mes = c1.get(Calendar.MONTH);
                int anio = c1.get(Calendar.YEAR);
                String fecha = "" + anio + "-" + mes + "-" + dia;
                int ruta1 = nuevoPa.nuevo.ruta(modelo.getValueAt(i, 1).toString());
                int tarifaG = nuevoPa.tarifaGlob;
                nuevoPa.nuevo.agregarDatosPaquete(codigo, ruta1, "BODEGA", destina, remitente, "", tarifaG, priorizacion, entNit.getText(), peso);
                nuevoPa.nuevo.agregarAGanancias(codigo, ruta1, Integer.parseInt(costo), fecha);
                nuevoPa.nuevo.agregarABodega1(codigo, ruta1, priorizacion);
                if (entNombreCliente.isEditable() && entCiudadCliente.isEditable() && entNit.getText().length()==8){
                    nuevoPa.nuevo.agregarCliente(entNit.getText(), entNombreCliente.getText(),entCiudadCliente.getText());
                } 
                JOptionPane.showMessageDialog(null, "PAQUETE INGRESADO EXITOSAMENTE");
                nuevoPa.limpiarTodo();
                this.dispose();
            }

        }

    }//GEN-LAST:event_btn_GenerarFacturaActionPerformed

    private void btn_BuscarNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarNitActionPerformed
        if (!entNit.getText().isBlank()){
            if (!entNit.getText().equalsIgnoreCase("cf") && !entNit.getText().equalsIgnoreCase("c/f")){
                if (entNit.getText().length()==8){
                    clientes = nuevoPa.nuevo.clienteNit(entNit.getText());
                    if (!clientes[0].equalsIgnoreCase("nuevo")){
                        entNombreCliente.setText(clientes[0]);
                        entCiudadCliente.setText(clientes[1]);
                        entNombreCliente.setEditable(false);
                        entCiudadCliente.setEditable(false);
                    }
                }
            } else {
                entNombreCliente.setText("C/F");
                entCiudadCliente.setText("C/F");
                entNombreCliente.setEditable(false);
                entCiudadCliente.setEditable(false);
            }
        }
        btn_GenerarFactura.setEnabled(true);
    }//GEN-LAST:event_btn_BuscarNitActionPerformed
    public void mostrarTabla(){
        modelo2 = new DefaultTableModel();
        modelo2.addColumn("DESCRIPCION");
        modelo2.addColumn("CANTIDAD");
        modelo2.addColumn("SUBTOTAL");
        tablaFactura.setModel(modelo2);
        String descripcion = "";
        String datos[] = new String[3];
        int priorizado = 0;
        int costoTotal = 0;
        for (int i = 0; i < modelo.getRowCount(); i++){
            String codigo = modelo.getValueAt(i, 0).toString();
            String ruta = modelo.getValueAt(i, 1).toString();
            String destina = modelo.getValueAt(i, 2).toString();
            String costo = modelo.getValueAt(i, 5).toString();
            String priori = modelo.getValueAt(i, 6).toString();
            costoTotal += Integer.parseInt(modelo.getValueAt(i, 5).toString());
            if(!priori.equalsIgnoreCase("no")){
                priorizado++;
            }
            datos[0] = "Paquete "+codigo+" en la ruta "+ruta+" a entregarselo a "+destina;
            datos[1] = "1";
            datos[2] = "Q"+costo+".00";
            modelo2.addRow(datos);
        }
        int tarifaPriori = nuevoPa.costos1[1];
        int totalPriori = priorizado*tarifaPriori;
        datos[0] = "Cuota EXTRA por PRIORIZACION ya incluida";
        datos[1] = ""+priorizado;
        datos[2] = "Q"+totalPriori+".00 (Ya incluido)";
        modelo2.addRow(datos);
        datos[0] = "Total";
        datos[1] = " ";
        datos[2] = "Q"+costoTotal+".00";
        modelo2.addRow(datos);
        tablaFactura.setModel(modelo2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarNit;
    private javax.swing.JButton btn_GenerarFactura;
    private javax.swing.JTextField entCiudadCliente;
    private javax.swing.JTextField entNit;
    private javax.swing.JTextField entNombreCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFactura;
    // End of variables declaration//GEN-END:variables
}
