/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paqueteria;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willians
 */
public class MostrarReportes extends javax.swing.JInternalFrame {
    PantallaPaqueteria pantalla;
    DefaultTableModel modelo1;
    Reportes reporte1;
    /**
     * Creates new form MostrarReportes
     */
    public MostrarReportes(PantallaPaqueteria pantalla) {
        initComponents();
        this.pantalla = pantalla;
        this.reporte1 = new Reportes(pantalla);
        inicioComponentes();
        panelReporte1.setVisible(true);
    }
    public MostrarReportes(PantallaPaqueteria pantalla, int i) {
        initComponents();
        this.pantalla = pantalla;
        this.reporte1 = new Reportes(pantalla);
        inicioComponentes();
        if (i==0){
            panelReporte2.setVisible(true);
        }else {
        
        }
    }
    public void inicioComponentes(){
        panelReporte1.setVisible(false);
        panelReporte2.setVisible(false);
        panelReporte3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelesReport = new javax.swing.JLayeredPane();
        panelReporte1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo_PaquetesRutas = new javax.swing.JComboBox<>();
        btn_Ver1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReporte1 = new javax.swing.JTable();
        btn_GenerarReporte1 = new javax.swing.JButton();
        panelReporte2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        entBusquedaCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_OpcionesCliente = new javax.swing.JComboBox<>();
        btn_BuscarCliente1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaReporteClientes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        panelReporte3 = new javax.swing.JPanel();

        setClosable(true);

        jLabel1.setText("PAQUETES EN RUTAS");

        combo_PaquetesRutas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVA", "INACTIVA", "TODO" }));

        btn_Ver1.setText("VER");
        btn_Ver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ver1ActionPerformed(evt);
            }
        });

        tablaReporte1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaReporte1);

        btn_GenerarReporte1.setText("GENERAR REPORTE");
        btn_GenerarReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenerarReporte1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReporte1Layout = new javax.swing.GroupLayout(panelReporte1);
        panelReporte1.setLayout(panelReporte1Layout);
        panelReporte1Layout.setHorizontalGroup(
            panelReporte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporte1Layout.createSequentialGroup()
                .addGroup(panelReporte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReporte1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelReporte1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(combo_PaquetesRutas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Ver1))
                    .addGroup(panelReporte1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReporte1Layout.createSequentialGroup()
                .addGap(0, 221, Short.MAX_VALUE)
                .addComponent(btn_GenerarReporte1)
                .addGap(191, 191, 191))
        );
        panelReporte1Layout.setVerticalGroup(
            panelReporte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporte1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReporte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_PaquetesRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Ver1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_GenerarReporte1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel2.setText("REPORTE CLIENTES");

        jLabel3.setText("BUSCAR POR:");

        combo_OpcionesCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIT", "Nombre", "Todo" }));

        btn_BuscarCliente1.setText("BUSCAR");
        btn_BuscarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarCliente1ActionPerformed(evt);
            }
        });

        tablaReporteClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaReporteClientes);

        jButton1.setText("GENERAR REPORTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReporte2Layout = new javax.swing.GroupLayout(panelReporte2);
        panelReporte2.setLayout(panelReporte2Layout);
        panelReporte2Layout.setHorizontalGroup(
            panelReporte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporte2Layout.createSequentialGroup()
                .addGroup(panelReporte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReporte2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelReporte2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(entBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_OpcionesCliente, 0, 135, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_BuscarCliente1))
                    .addGroup(panelReporte2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReporte2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(198, 198, 198))
        );
        panelReporte2Layout.setVerticalGroup(
            panelReporte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporte2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReporte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(combo_OpcionesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BuscarCliente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelReporte3Layout = new javax.swing.GroupLayout(panelReporte3);
        panelReporte3.setLayout(panelReporte3Layout);
        panelReporte3Layout.setHorizontalGroup(
            panelReporte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        panelReporte3Layout.setVerticalGroup(
            panelReporte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        panelesReport.setLayer(panelReporte1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelesReport.setLayer(panelReporte2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelesReport.setLayer(panelReporte3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelesReportLayout = new javax.swing.GroupLayout(panelesReport);
        panelesReport.setLayout(panelesReportLayout);
        panelesReportLayout.setHorizontalGroup(
            panelesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
            .addGroup(panelesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelReporte1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelReporte2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelReporte3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelesReportLayout.setVerticalGroup(
            panelesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
            .addGroup(panelesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelReporte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelReporte2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelReporte3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelesReport)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelesReport)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Ver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ver1ActionPerformed
        String queEs = combo_PaquetesRutas.getSelectedItem().toString();

        if (queEs.equalsIgnoreCase("activa")) {
            modelo1 = null;
            modelo1 = new DefaultTableModel();
            modelo1.addColumn("CODIGO");
            modelo1.addColumn("# PUNTOS");
            modelo1.addColumn("DESTINO");
            modelo1.addColumn("CUOTA DESTINO");
            modelo1.addColumn("CUOTA PRIORIDAD");
            modelo1.addColumn("TARIFA PESO");
            modelo1.addColumn("PAQUETES EN RUTA");
            tablaReporte1.setModel(modelo1);
            tablaReporte1.setEnabled(false);
            agregarDatosTablas(true);
        } else {
            if (queEs.equalsIgnoreCase("inactiva")) {
                modelo1 = null;
                modelo1 = new DefaultTableModel();
                modelo1.addColumn("CODIGO");
                modelo1.addColumn("# PUNTOS");
                modelo1.addColumn("DESTINO");
                modelo1.addColumn("CUOTA DESTINO");
                modelo1.addColumn("CUOTA PRIORIDAD");
                modelo1.addColumn("TARIFA PESO");
                modelo1.addColumn("PAQUETES FUERA DE LA RUTA");
                tablaReporte1.setModel(modelo1);
                tablaReporte1.setEnabled(false);
                agregarDatosTablas(false);
            } else {
                modelo1 = null;
                modelo1 = new DefaultTableModel();
                modelo1.addColumn("CODIGO");
                modelo1.addColumn("# PUNTOS");
                modelo1.addColumn("DESTINO");
                modelo1.addColumn("CUOTA DESTINO");
                modelo1.addColumn("CUOTA PRIORIDAD");
                modelo1.addColumn("TARIFA PESO");
                modelo1.addColumn("PAQUETES EN LA RUTA");
                modelo1.addColumn("PAQUETES FUERA DE LA RUTA");
                tablaReporte1.setModel(modelo1);
                tablaReporte1.setEnabled(false);
                String sql2 = "SELECT * FROM Ruta";
            Statement st;
            try {
                st = pantalla.controladorDB.cn.createStatement();
                ResultSet rs = st.executeQuery(sql2);
                while (rs.next()) {
                    int cod = rs.getInt("codigo_ruta");
                    int no_puntos = rs.getInt("no_puntos");
                    String destino = rs.getString("destino");
                    int cuota_destino = rs.getInt("cuota_destino");
                    int cuota_priori = rs.getInt("cuota_priori");
                    int tarifa_peso = rs.getInt("tarifa_peso");
                    int cuantosHay1 = pantalla.controladorDB.paquetesEnRuta(cod,true);
                    int cuantosHay2 = pantalla.controladorDB.paquetesEnRuta(cod,false);
                    Object[] datos = new Object[8];
                    datos[0] = cod;
                    datos[1] = no_puntos;
                    datos[2] = destino;
                    datos[3] = cuota_destino;
                    datos[4] = cuota_priori;
                    datos[5] = tarifa_peso;
                    datos[6] = cuantosHay1;
                    datos[7] = cuantosHay2;
                    modelo1.addRow(datos);
                }
                tablaReporte1.setModel(modelo1);
            } catch (SQLException e) {
                System.out.print("problema" + e.getMessage());
            }
            }

        }
    }//GEN-LAST:event_btn_Ver1ActionPerformed

    private void btn_GenerarReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenerarReporte1ActionPerformed
        if (combo_PaquetesRutas.getSelectedItem().toString().equalsIgnoreCase("todo")){
            reporte1.generarReporte();
        } else if (combo_PaquetesRutas.getSelectedItem().toString().equalsIgnoreCase("inactiva")){
            reporte1.generarReporte(false);
        } else {
            reporte1.generarReporte(true);
        }
    }//GEN-LAST:event_btn_GenerarReporte1ActionPerformed

    private void btn_BuscarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarCliente1ActionPerformed
        if (combo_OpcionesCliente.getSelectedItem().toString().equalsIgnoreCase("nit")) {
            String nit = entBusquedaCliente.getText();
            if (nit.length() == 8) {
                String[] datos1 = {" "," "};
                String[] costos = {"0","0","0"};
                if (esNumero1(nit)) {
                    String sql2 = "SELECT id_paquete FROM Paquetes WHERE nit = '"+nit+"'";
                    Statement st;
                    try {
                        st = pantalla.controladorDB.cn.createStatement();
                        ResultSet rs = st.executeQuery(sql2);
                        modelo1 = new DefaultTableModel();
                        modelo1.addColumn("NIT");
                        modelo1.addColumn("PAQUETE");
                        modelo1.addColumn("NOMBRE");
                        modelo1.addColumn("CIUDAD");
                        modelo1.addColumn("INGRESO");
                        modelo1.addColumn("COSTO");
                        modelo1.addColumn("GANANCIA");
                        tablaReporteClientes.setModel(modelo1);
                        while (rs.next()) {
                            String paquete = rs.getString("id_paquete");
                            costos = pantalla.controladorDB.ganancias1(paquete);
                            datos1 = pantalla.controladorDB.datosCliente(nit);
                            agregarDatosTablas2(costos,datos1,nit,paquete);
                        }
                        tablaReporteClientes.setModel(modelo1);
                    } catch (SQLException e) {
                        System.out.print("problema" + e.getMessage());
                    }
                }
            }
        } else {
            if (combo_OpcionesCliente.getSelectedItem().toString().equalsIgnoreCase("todo"))
            {
                String[] datos1 = {" "," "};
                String[] costos = {"0","0","0"};
              
                String sql2 = "SELECT id_paquete,nit FROM Paquetes";
                    Statement st;
                    try {
                        st = pantalla.controladorDB.cn.createStatement();
                        ResultSet rs = st.executeQuery(sql2);
                        modelo1 = new DefaultTableModel();
                        modelo1.addColumn("NIT");
                        modelo1.addColumn("PAQUETE");
                        modelo1.addColumn("NOMBRE");
                        modelo1.addColumn("CIUDAD");
                        modelo1.addColumn("INGRESO");
                        modelo1.addColumn("COSTO");
                        modelo1.addColumn("GANANCIA");
                        tablaReporteClientes.setModel(modelo1);
                        while (rs.next()) {
                            String paquete = rs.getString("id_paquete");
                            String nit = rs.getString("nit");
                            costos = pantalla.controladorDB.ganancias1(paquete);
                            datos1 = pantalla.controladorDB.datosCliente(nit);
                            agregarDatosTablas2(costos,datos1,nit,paquete);
                        }
                        tablaReporteClientes.setModel(modelo1);
                    } catch (SQLException e) {
                        System.out.print("problema" + e.getMessage());
                    }
            } else {
                String[] datos1 = {" "," "};
                String[] costos = {"0","0","0"};
                String nit1 = "";
                String sql = "SELECT nit_1 FROM Clientes WHERE nombre = '"+entBusquedaCliente.getText()+"'";
                Statement st2;
                
                    try {
                        st2 = pantalla.controladorDB.cn.createStatement();
                        ResultSet rs2 = st2.executeQuery(sql);
                        
                        while (rs2.next()){
                            nit1 = rs2.getString("nit_1");
                        }
                    }catch (SQLException se){
                    
                    
                    }
                    String sql2 = "SELECT id_paquete FROM Paquetes WHERE nit = '"+nit1+"'";
                    Statement st;
                    try {
                        st = pantalla.controladorDB.cn.createStatement();
                        ResultSet rs = st.executeQuery(sql2);
                        modelo1 = new DefaultTableModel();
                        modelo1.addColumn("NIT");
                        modelo1.addColumn("PAQUETE");
                        modelo1.addColumn("NOMBRE");
                        modelo1.addColumn("CIUDAD");
                        modelo1.addColumn("INGRESO");
                        modelo1.addColumn("COSTO");
                        modelo1.addColumn("GANANCIA");
                        tablaReporteClientes.setModel(modelo1);
                        while (rs.next()) {
                            String paquete = rs.getString("id_paquete");
                            costos = pantalla.controladorDB.ganancias1(paquete);
                            datos1 = pantalla.controladorDB.datosCliente(nit1);
                            agregarDatosTablas2(costos,datos1,nit1,paquete);
                        }
                        tablaReporteClientes.setModel(modelo1);
                    } catch (SQLException e) {
                        System.out.print("problema" + e.getMessage());
                    }
            
            }
        }
    }//GEN-LAST:event_btn_BuscarCliente1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Reportes reporte2 = new Reportes(pantalla);
        reporte2.generarReporteClientes(modelo1);
    }//GEN-LAST:event_jButton1ActionPerformed
    public boolean esNumero1(String numero){
        String numeros = "0123456789";
        int longitud = numeros.length();
        int longitud2 = numero.length();
        int correcto = 0;
        for (int i = 0; i < longitud2; i++){
            for (int u = 0; u < longitud; u++){
                if (numeros.charAt(u)==numero.charAt(i)){
                    correcto++;
                }
            }
        }
        return correcto==longitud2;
    }
    
    public void agregarDatosTablas(boolean si1) {
        String sql2 = "SELECT * FROM Ruta";
        Statement st;
        try {
            st = pantalla.controladorDB.cn.createStatement();
            ResultSet rs = st.executeQuery(sql2);
            while (rs.next()) {
                int cod = rs.getInt("codigo_ruta");
                int no_puntos = rs.getInt("no_puntos");
                String destino = rs.getString("destino");
                int cuota_destino = rs.getInt("cuota_destino");
                int cuota_priori = rs.getInt("cuota_priori");
                int tarifa_peso = rs.getInt("tarifa_peso");
                int cuantosHay1 = pantalla.controladorDB.paquetesEnRuta(cod, si1);
                Object[] datos = new Object[7];
                datos[0] = cod;
                datos[1] = no_puntos;
                datos[2] = destino;
                datos[3] = cuota_destino;
                datos[4] = cuota_priori;
                datos[5] = tarifa_peso;
                datos[6] = cuantosHay1;
                modelo1.addRow(datos);
            }
            tablaReporte1.setModel(modelo1);
        } catch (SQLException e) {
            System.out.print("problema" + e.getMessage());
        }
    }
    public void agregarDatosTablas2(String[] costos, String[] datos1, String nit, String paquete) {
        Object[] datos = new Object[7];
        datos[0] = nit;
        datos[1] = paquete;
        datos[2] = datos1[0];
        datos[3] = datos1[1];
        datos[4] = costos[0];
        datos[5] = costos[1];
        datos[6] = costos[2];
        modelo1.addRow(datos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarCliente1;
    private javax.swing.JButton btn_GenerarReporte1;
    private javax.swing.JButton btn_Ver1;
    private javax.swing.JComboBox<String> combo_OpcionesCliente;
    private javax.swing.JComboBox<String> combo_PaquetesRutas;
    private javax.swing.JTextField entBusquedaCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelReporte1;
    private javax.swing.JPanel panelReporte2;
    private javax.swing.JPanel panelReporte3;
    private javax.swing.JLayeredPane panelesReport;
    private javax.swing.JTable tablaReporte1;
    private javax.swing.JTable tablaReporteClientes;
    // End of variables declaration//GEN-END:variables
}
